# Site settings
title: everything is grEAT
email: clifreeder@gmail.com
username: clifff
description: "Probably the definitive web presence of Clif Reeder"
baseurl: ""
url: "https://clifff.com"
timezone: America/New_York
exclude: [s3_website.yml, Gemfile, Gemfile.lock, Rakefile, vendor/]

# Build settings
markdown: kramdown
permalink: pretty
