# Site settings
title: everything is grEAT
email: clifreeder@gmail.com
description: "Probably the definitive web presence of Clif Reeder"
baseurl: ""
url: "http://clifff.com"
exclude: [s3_website.yml, Gemfile, Rakefile]

# Build settings
markdown: kramdown
permalink: pretty
